name: Package compiler

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  compile:
    name: 'Compile'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: 'npm run compile'

      - run: 'cp README.md package.json LICENSE ./dist'

      - uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: package
