name: Test & Format & Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  TestFormatLint:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: "~/.npm"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: "npm install"

      - run: npm run test && npm run format && npm run lint
        env:
          ACCESS_SECRET: a
          REFRESH_SECRET: a
