name: Build & Test & Format & Lint

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 'Test & Format & Lint'

    runs-on: ubuntu-latest

    timeout-minutes: 5

    permissions:
      contents: write
      actions: write
      checks: write

    services:
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: actions/cache/restore@v4
        with:
          path: './node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('./package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: 'npm install'

      - name: Run tests
        run: |
          npx jest --coverage | tee ./coverage.txt && exit ${PIPESTATUS[0]}

      - run: npm run test && npm run format && npm run lint
        env:
          ACCESS_SECRET: a
          REFRESH_SECRET: a

      - uses: stefanzweifel/git-auto-commit-action@v5

      - uses: actions/cache/save@v4
        if: always()
        with:
          path: './node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('./package.json') }}

      - uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: test-results
          path: ./reports/*.xml # Path to test results
          reporter: jest-junit

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        id: coverageComment
        with:
          title: Test report
          junitxml-path: ./reports/junit.xml
          junitxml-title: JUnit
          coverage-summary-path: ./coverage/coverage-summary.json
          coverage-title: Coverage result
          coverage-path: ./coverage/coverage.txt
